---
- name: Override build path (so I can push to git repo)
  ansible.builtin.set_fact:
    build_ee_dest_dir: "{{ playbook_dir }}/vars/{{ execution_environment }}/__build"

- name: "Build Execution Environment"
  vars:
    build_ee_main_var_name: "vars_for_loop_{{ ee_idx }}"
  ansible.builtin.import_role:
    name: build_ee
...
