---
version: 3
dependencies:
  ansible_core:
      package_pip: ansible-core==2.15
  ansible_runner:
      package_pip: ansible-runner
  python: requirements.txt
additional_build_steps:
  prepend_base:
    - RUN curl -o ./libisofs.rpm https://repo.almalinux.org/almalinux/9/AppStream/x86_64/os/Packages/libisofs-1.5.4-4.el9.x86_64.rpm
    - RUN curl -o ./libburn.rpm https://repo.almalinux.org/almalinux/9/AppStream/x86_64/os/Packages/libburn-1.5.4-5.el9.x86_64.rpm
    - RUN curl -o ./libisoburn.rpm https://repo.almalinux.org/almalinux/9/AppStream/x86_64/os/Packages/libisoburn-1.5.4-5.el9_5.x86_64.rpm
    - RUN curl -o ./xorriso.rpm https://repo.almalinux.org/almalinux/9/AppStream/x86_64/os/Packages/xorriso-1.5.4-5.el9_5.x86_64.rpm
    - RUN rpm -i ./libisofs.rpm ./libburn.rpm ./libisoburn.rpm ./xorriso.rpm
  append_final:
    - RUN dnf clean all && rm -rf /var/cache/yum
options:
  package_manager_path: /usr/bin/dnf
images:
  base_image:
    name: registry.access.redhat.com/ubi9/ubi:latest
    signature_original_name: registry.access.redhat.com/ubi9/ubi:latest