---
version: 3
dependencies:
  ansible_core:
      package_pip: ansible-core==2.15
  ansible_runner:
      package_pip: ansible-runner
  python: requirements.txt
additional_build_steps:
  prepend_base:
    - RUN subscription-manager register --activationkey={{ rhel_activationkey }} --org={{ rhel_org }}
  append_base:
    - RUN dnf install -y xorriso
  append_final:
    - RUN dnf clean all && rm -rf /var/cache/yum
    - RUN subscription-manager unregister
options:
  package_manager_path: /usr/bin/dnf
images:
  base_image:
    name: registry.access.redhat.com/ubi9/ubi:latest
    signature_original_name: registry.access.redhat.com/ubi9/ubi:latest